# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-07 14:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20170107_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2017, 1, 7, 14, 15, 11, 645605, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
